-- Core visitor events table
CREATE TABLE visitor_events (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamptz DEFAULT now(),
  visitor_hash  text NOT NULL,            -- FingerprintJS visitorId (SHA-256 hashed)
  session_id    text NOT NULL,            -- Per-tab session UUID
  page_path     text DEFAULT '/',
  referrer      text,
  user_agent    text,
  screen_width  int,
  screen_height int,
  language      text,
  timezone      text,
  is_mobile     boolean DEFAULT false,
  country       text                      -- Derived from headers
);

-- Unique visitors aggregate view
CREATE OR REPLACE VIEW unique_visitors AS
  SELECT
    visitor_hash,
    MIN(created_at) AS first_seen,
    MAX(created_at) AS last_seen,
    COUNT(*)        AS total_visits
  FROM visitor_events
  GROUP BY visitor_hash;

-- Index for fast lookups
CREATE INDEX idx_visitor_hash ON visitor_events (visitor_hash);
CREATE INDEX idx_created_at   ON visitor_events (created_at);

-- Set Row Level Security (RLS)
ALTER TABLE visitor_events ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (from edge function via anon key)
CREATE POLICY "Enable insert for anonymous users" ON visitor_events
    FOR INSERT WITH CHECK (true);

-- Allow reads for dashboard via edge function
CREATE POLICY "Enable read for anonymous users" ON visitor_events
    FOR SELECT USING (true);
